### PR TITLE
Introducing the bootstrap css version of the website!

### PR DESCRIPTION
**Pull request by wgyt**
^^^
CC: @D1WK @Voxalice

### CODE REVIEW

**Review by D1WK — APPROVED** [review]
This is amazing! The site looks so nice!

**Comment by AwayFromKeyword** [comment]
@all-contributors please add @wgyt for code,ideas

**Comment by AwayFromKeyword** [comment]
@all-contributors please add wgyt for code,ideas

**Comment by AwayFromKeyword** [comment]
@all-contributors please add @wgyt for code,ideas

**Comment by AwayFromKeyword** [comment]
@all-contributors please add @wgyt for code

**Comment by AwayFromKeyword** [comment]
FINALLY

**Pull request merged**
